version: '3'

services:
  mysql:
    container_name: list-db
    image: mysql
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3306:3306
    volumes: 
      - "./backend/migration.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      timeout: 10s
      retries: 10
      start_period: 10s

  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    restart: 'always'
    command: npm run dev
    volumes:
      - './backend/src:/app/src'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PORT=3001
      - SECRET=secret
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5

networks:
  default:
    name: ebytr_net
